import express from 'express';
const router = express.Router();

const CELEBRITIES = [
  {
    id: 'gdragon',
    name: '지드래곤',
    realName: '권지용',
    category: '가수',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/G-DRAGON_CHANEL_Photo_Call_1.jpg/250px-G-DRAGON_CHANEL_Photo_Call_1.jpg',
    postCount: 10,
    styles: [
      { label: '미니멀', count: 2, color: '#111' },
      { label: '포멀', count: 3, color: '#059669' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
      { label: '페미닌', count: 2, color: '#ec4899' },
    ],
    description: '패션 아이콘 지드래곤의 독보적인 스타일. 샤넬 앰배서더로서 하이패션과 스트릿의 경계를 허무는 GD만의 아방가르드한 룩을 만나보세요.',
  },
  {
    id: 'iu',
    name: '아이유',
    realName: '이지은',
    category: '가수',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/IU_at_Blue_Dragon_Series_Awards_on_18072025_%2810%29.png/250px-IU_at_Blue_Dragon_Series_Awards_on_18072025_%2810%29.png',
    postCount: 12,
    styles: [
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
      { label: '페미닌', count: 2, color: '#ec4899' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '단아하고 깔끔한 미니멀 스타일부터 러블리한 걸리시 룩까지 다양한 스타일을 소화하는 아이유의 패션을 모아봤어요.',
  },
  {
    id: 'jennie',
    name: '제니',
    realName: '김제니',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Jennie_2026_GDA_1.jpg/250px-Jennie_2026_GDA_1.jpg',
    postCount: 14,
    styles: [
      { label: '미니멀', count: 2, color: '#111' },
      { label: '캐주얼', count: 4, color: '#6366f1' },
      { label: '포멀', count: 3, color: '#059669' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
    ],
    description: '블랙핑크 제니의 시크하고 트렌디한 패션. 스트릿부터 하이패션까지 완벽하게 소화하는 제니만의 스타일을 살펴보세요.',
  },
  {
    id: 'winter',
    name: '윈터',
    realName: '김민정',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Winter_at_Kilian_Paris_event_on_27012026_%284%29.png/250px-Winter_at_Kilian_Paris_event_on_27012026_%284%29.png',
    postCount: 10,
    styles: [
      { label: '걸리시', count: 4, color: '#f59e0b' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
      { label: '미니멀', count: 1, color: '#111' },
    ],
    description: '에스파 윈터의 청순하면서도 세련된 패션. 걸리시한 무드와 모던한 감각이 공존하는 윈터의 스타일을 모아봤어요.',
  },
  {
    id: 'v',
    name: '뷔',
    realName: '김태형',
    searchKeyword: 'BTS 뷔',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/BTS%27s_V_20251004_04.jpg/250px-BTS%27s_V_20251004_04.jpg',
    postCount: 11,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '포멀', count: 3, color: '#059669' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
      { label: '페미닌', count: 2, color: '#ec4899' },
    ],
    description: 'BTS 뷔의 독보적인 아트적 감성과 럭셔리 패션. 루이비통 앰배서더로서 세계적인 주목을 받는 뷔의 패션 센스를 만나보세요.',
  },
  {
    id: 'jisoo',
    name: '지수',
    realName: '김지수',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Jisoo_at_Boyfriend_on_Demand_press_conference_on_26022026_%2812%29.png/250px-Jisoo_at_Boyfriend_on_Demand_press_conference_on_26022026_%2812%29.png',
    postCount: 13,
    styles: [
      { label: '페미닌', count: 5, color: '#ec4899' },
      { label: '걸리시', count: 3, color: '#f59e0b' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '블랙핑크 지수의 우아하고 사랑스러운 패션. 디올 앰배서더로서 로맨틱하면서도 시크한 스타일을 완성하는 지수의 룩을 살펴보세요.',
  },
  {
    id: 'leemin',
    name: '이민호',
    realName: '이민호',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Lee_Min-ho_in_December_2025.png/250px-Lee_Min-ho_in_December_2025.png',
    postCount: 9,
    styles: [
      { label: '포멀', count: 4, color: '#059669' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '한류 대표 배우 이민호의 남성적이면서도 세련된 패션. 드라마 속 캐릭터와 실제 일상에서도 완벽한 스타일을 유지하는 이민호의 룩을 모아봤어요.',
  },
  {
    id: 'songhyekyo',
    name: '송혜교',
    realName: '송혜교',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Song_Hye_Kyo_2025_%EC%86%A1%ED%98%9C%EA%B5%90_04.jpg/250px-Song_Hye_Kyo_2025_%EC%86%A1%ED%98%9C%EA%B5%90_04.jpg',
    postCount: 10,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '포멀', count: 3, color: '#059669' },
      { label: '페미닌', count: 2, color: '#ec4899' },
      { label: '캐주얼', count: 1, color: '#6366f1' },
    ],
    description: '시대를 초월한 아름다움을 지닌 배우 송혜교의 미니멀하고 고급스러운 패션. 샤넬 앰배서더로서 우아한 프렌치 시크 스타일을 완성하는 송혜교의 룩을 만나보세요.',
  },
  {
    id: 'suzy',
    name: '수지',
    realName: '배수지',
    category: '배우/가수',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Suzy_at_the_Longines_2026_new_product_presentation%2C_25_March_2026_04.png/250px-Suzy_at_the_Longines_2026_new_product_presentation%2C_25_March_2026_04.png',
    postCount: 11,
    styles: [
      { label: '캐주얼', count: 4, color: '#6366f1' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '미니멀', count: 2, color: '#111' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
    ],
    description: '청순한 이미지와 세련된 감각을 동시에 지닌 수지의 패션. 편안한 캐주얼부터 우아한 페미닌 룩까지 다양한 스타일을 자연스럽게 소화하는 수지의 매력을 살펴보세요.',
  },
  {
    id: 'chaeunwoo',
    name: '차은우',
    realName: '이동민',
    category: '아이돌/배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Cha_Eun-woo%2C_March_31%2C_2025.png/250px-Cha_Eun-woo%2C_March_31%2C_2025.png',
    postCount: 8,
    styles: [
      { label: '포멀', count: 3, color: '#059669' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '완벽한 외모와 패션 감각을 겸비한 차은우. 슈트부터 캐주얼까지 무엇을 입어도 빛나는 차은우의 스타일리시한 룩을 모아봤어요.',
  },
  {
    id: 'rose',
    name: '로제',
    realName: '박채영',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Blackpink_Ros%C3%A9_Rimowa_1.jpg/250px-Blackpink_Ros%C3%A9_Rimowa_1.jpg',
    postCount: 12,
    styles: [
      { label: '걸리시', count: 3, color: '#f59e0b' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
    ],
    description: '블랙핑크 로제의 독창적이고 감각적인 패션. 티파니 앰배서더로서 보헤미안 감성과 하이패션을 넘나드는 로제의 유니크한 스타일을 살펴보세요.',
  },
  {
    id: 'parkseojun',
    name: '박서준',
    realName: '박서준',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Park_Seo-joon_in_March_2026.png/250px-Park_Seo-joon_in_March_2026.png',
    postCount: 9,
    styles: [
      { label: '캐주얼', count: 4, color: '#6366f1' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '남성미 넘치는 배우 박서준의 자연스럽고 세련된 패션. 편안한 스트릿 캐주얼부터 깔끔한 포멀룩까지 다양하게 소화하는 박서준의 스타일을 모아봤어요.',
  },
  {
    id: 'irene',
    name: '아이린',
    realName: '배주현',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/250320_%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3_Irene_UGG_Photo_Call.jpg/250px-250320_%EB%A0%88%EB%93%9C%EB%B2%A8%EB%B2%B3_Irene_UGG_Photo_Call.jpg',
    postCount: 10,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
      { label: '포멀', count: 1, color: '#059669' },
    ],
    description: '레드벨벳 아이린의 청순하고 완벽한 패션. 단정한 미니멀 스타일부터 사랑스러운 페미닌 룩까지 아이린만의 완성도 높은 스타일을 만나보세요.',
  },
  {
    id: 'kimsuhyun',
    name: '김수현',
    realName: '김수현',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Kim_Soo-hyun_in_August_2024_-_2.png/250px-Kim_Soo-hyun_in_August_2024_-_2.png',
    postCount: 0,
    styles: [
      { label: '포멀', count: 4, color: '#059669' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '탑배우 김수현의 세련되고 남성미 넘치는 패션. 드라마 속 완벽한 스타일링부터 일상의 캐주얼 룩까지 김수현만의 감각을 살펴보세요.',
  },
  {
    id: 'hyunbin',
    name: '현빈',
    realName: '김태평',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Hyun_Bin_at_the_2024_Toronto_International_Film_Festival_2_%28cropped%29.jpg/250px-Hyun_Bin_at_the_2024_Toronto_International_Film_Festival_2_%28cropped%29.jpg',
    postCount: 0,
    styles: [
      { label: '포멀', count: 5, color: '#059669' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '한류 대표 배우 현빈의 고급스럽고 클래식한 패션. 세련된 슈트 스타일부터 캐주얼 룩까지 완벽하게 소화하는 현빈의 매력을 만나보세요.',
  },
  {
    id: 'sonyejin',
    name: '손예진',
    realName: '손예진',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Son_Ye-jin_at_the_2025_Blue_Dragon_Film_Awards_3.png/250px-Son_Ye-jin_at_the_2025_Blue_Dragon_Film_Awards_3.png',
    postCount: 0,
    styles: [
      { label: '페미닌', count: 4, color: '#ec4899' },
      { label: '포멀', count: 3, color: '#059669' },
      { label: '미니멀', count: 3, color: '#111' },
    ],
    description: '우아하고 고혹적인 배우 손예진의 패션. 레드카펫을 빛내는 드레스부터 일상의 여유로운 스타일까지 손예진만의 품격 있는 룩을 살펴보세요.',
  },
  {
    id: 'gongyoo',
    name: '공유',
    realName: '공지철',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Gong_Yoo_in_2021_-_3.png/250px-Gong_Yoo_in_2021_-_3.png',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
      { label: '포멀', count: 3, color: '#059669' },
    ],
    description: '도깨비 남자배우 공유의 지적이고 세련된 패션. 깔끔한 미니멀 스타일부터 트렌치코트로 완성하는 시크한 룩까지 공유의 스타일을 모아봤어요.',
  },
  {
    id: 'leejongsuk',
    name: '이종석',
    realName: '이종석',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/240725_Lee_Jong-suk.png/250px-240725_Lee_Jong-suk.png',
    postCount: 0,
    styles: [
      { label: '캐주얼', count: 4, color: '#6366f1' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '배우 이종석의 트렌디하고 도시적인 패션. 스트릿 감성의 캐주얼부터 드레시한 포멀 룩까지 이종석만의 유니크한 스타일을 살펴보세요.',
  },
  {
    id: 'junjihyun',
    name: '전지현',
    realName: '왕지현',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Jun_Ji-hyun_in_April_2026.png/250px-Jun_Ji-hyun_in_April_2026.png',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '포멀', count: 4, color: '#059669' },
      { label: '페미닌', count: 2, color: '#ec4899' },
    ],
    description: '시대를 초월한 배우 전지현의 우아하고 강인한 패션. 천만 영화 속 아이코닉한 룩부터 럭셔리 패션 위크까지 전지현의 클래식한 스타일을 만나보세요.',
  },
  {
    id: 'namjoohyuk',
    name: '남주혁',
    realName: '남주혁',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Nam_Joo-hyuk_%EB%82%A8%EC%A3%BC%ED%98%81_-_Photoshoot_for_Marie_Claire_Korea_in_December_2020_%282%29.jpg/250px-Nam_Joo-hyuk_%EB%82%A8%EC%A3%BC%ED%98%81_-_Photoshoot_for_Marie_Claire_Korea_in_December_2020_%282%29.jpg',
    postCount: 0,
    styles: [
      { label: '캐주얼', count: 4, color: '#6366f1' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '모델 출신 배우 남주혁의 롱다리를 활용한 스타일리시한 패션. 스포티한 캐주얼부터 클린한 포멀 룩까지 남주혁의 모델 DNA가 빛나는 스타일을 살펴보세요.',
  },
  {
    id: 'parkminyoung',
    name: '박민영',
    realName: '박민영',
    category: '배우',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/20250625_Park_Min-young_TAG_Heuer_PhotoCall.jpg/250px-20250625_Park_Min-young_TAG_Heuer_PhotoCall.jpg',
    postCount: 0,
    styles: [
      { label: '페미닌', count: 4, color: '#ec4899' },
      { label: '걸리시', count: 3, color: '#f59e0b' },
      { label: '미니멀', count: 2, color: '#111' },
    ],
    description: '사랑스럽고 세련된 배우 박민영의 패션. 드라마 속 오피스룩부터 일상의 청순한 페미닌 스타일까지 박민영의 감각적인 룩을 모아봤어요.',
  },
  {
    id: 'jimin',
    name: '지민',
    realName: '박지민',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Jimin_on_the_way_to_SBS_Radio%2C_31_March_2023_%282%29.jpg/250px-Jimin_on_the_way_to_SBS_Radio%2C_31_March_2023_%282%29.jpg',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 3, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '포멀', count: 3, color: '#059669' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: 'BTS 지민의 섬세하고 아름다운 패션. 디올 앰배서더로서 고혹적인 하이패션부터 무대 위 파워풀한 퍼포먼스 의상까지 지민만의 독보적인 스타일을 만나보세요.',
  },
  {
    id: 'jungkook',
    name: '정국',
    realName: '전정국',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Jung_Kook_of_BTS%2C_February_12%2C_2026_%281%29.png/250px-Jung_Kook_of_BTS%2C_February_12%2C_2026_%281%29.png',
    postCount: 0,
    styles: [
      { label: '캐주얼', count: 4, color: '#6366f1' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: 'BTS 정국의 자유롭고 강렬한 패션. 칼크아인 앰배서더로서 스트릿 캐주얼부터 럭셔리 하이패션까지 정국만의 글로벌 감성을 살펴보세요.',
  },
  {
    id: 'lisa',
    name: '리사',
    realName: '랄리사 마노발',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/20240314_Lisa_Manoban_07.jpg/250px-20240314_Lisa_Manoban_07.jpg',
    postCount: 0,
    styles: [
      { label: '스트릿', count: 4, color: '#7c3aed' },
      { label: '걸리시', count: 3, color: '#f59e0b' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '블랙핑크 리사의 파격적이고 글로벌한 패션. 셀린느 앰배서더로서 스트릿 힙합 스타일부터 하이패션까지 전 세계를 사로잡는 리사의 아이코닉한 룩을 모아봤어요.',
  },
  {
    id: 'karina',
    name: '카리나',
    realName: '유지민',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Karina_at_Love_Your_W_event_2025.jpg/250px-Karina_at_Love_Your_W_event_2025.jpg',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '에스파 리더 카리나의 완벽하고 세련된 패션. 지오르지오 아르마니 앰배서더로서 차가운 미녀 이미지와 사랑스러운 걸리시 룩을 자유롭게 오가는 카리나의 스타일을 살펴보세요.',
  },
  {
    id: 'taeyeon',
    name: '태연',
    realName: '김태연',
    category: '가수',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/250307_Taeyeon_%40_-The_Tense-_in_Seoul_Day_1_%2854371295597%29_%28cropped%29.jpg/250px-250307_Taeyeon_%40_-The_Tense-_in_Seoul_Day_1_%2854371295597%29_%28cropped%29.jpg',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
    ],
    description: '소녀시대 태연의 시간이 지나도 변치 않는 아름다운 패션. 청순하고 깔끔한 미니멀부터 우아한 페미닌 스타일까지 태연만의 감성 룩을 모아봤어요.',
  },
  {
    id: 'yoona',
    name: '윤아',
    realName: '임윤아',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/250911_YOONA_%40_SULWHASOOSecret_House_Pop-up_Open_05_%28cropped%29.jpg/250px-250911_YOONA_%40_SULWHASOOSecret_House_Pop-up_Open_05_%28cropped%29.jpg',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '소녀시대 윤아의 영원한 국민 첫사랑 스타일. 설화수 앰배서더로서 청순하고 우아한 패션부터 트렌디한 캐주얼까지 윤아의 사랑스러운 룩을 살펴보세요.',
  },
  {
    id: 'kangdaniel',
    name: '강다니엘',
    realName: '강다니엘',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Kang_Daniel_at_Music_Bank_-_2024-09-26.png/250px-Kang_Daniel_at_Music_Bank_-_2024-09-26.png',
    postCount: 0,
    styles: [
      { label: '스트릿', count: 4, color: '#7c3aed' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
      { label: '포멀', count: 2, color: '#059669' },
    ],
    description: '강다니엘의 스트릿 감성 넘치는 트렌디한 패션. 힙합 캐주얼부터 세련된 포멀 룩까지 강다니엘만의 에너지 넘치는 스타일을 모아봤어요.',
  },
  {
    id: 'minji',
    name: '민지',
    realName: '김민지',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Minji_Olens_2024_FW_1.jpg/250px-Minji_Olens_2024_FW_1.jpg',
    postCount: 0,
    styles: [
      { label: '걸리시', count: 4, color: '#f59e0b' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
    ],
    description: '뉴진스 리더 민지의 청순하고 트렌디한 Y2K 감성 패션. 세일러 문 스타일부터 모던 캐주얼까지 민지가 선도하는 최신 패션 트렌드를 살펴보세요.',
  },
  {
    id: 'kazuha',
    name: '카즈하',
    realName: '나카무라 카즈하',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Kazuha_of_Le_Sserafim%2C_April_5%2C_2024_%284%29.png/250px-Kazuha_of_Le_Sserafim%2C_April_5%2C_2024_%284%29.png',
    postCount: 0,
    styles: [
      { label: '미니멀', count: 4, color: '#111' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '르세라핌 카즈하의 발레리나 감성과 세련된 패션. 발레 베이스의 우아한 무드와 K-팝 트렌드가 어우러진 카즈하만의 독특한 스타일을 만나보세요.',
  },
  {
    id: 'ryujin',
    name: '류진',
    realName: '신류진',
    category: '아이돌',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/251110_Shin_Ryujin_from_ITZY.png/250px-251110_Shin_Ryujin_from_ITZY.png',
    postCount: 0,
    styles: [
      { label: '스트릿', count: 4, color: '#7c3aed' },
      { label: '캐주얼', count: 3, color: '#6366f1' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
    ],
    description: 'ITZY 류진의 강렬하고 쿨한 걸크러시 패션. 스트릿 스타일부터 퍼포먼스 의상까지 류진만의 파워풀한 에너지를 담은 룩을 살펴보세요.',
  },
  {
    id: 'limyoungwoong',
    name: '임영웅',
    realName: '임영웅',
    category: '가수',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Temp_1662384481565.-511956263.jpg/250px-Temp_1662384481565.-511956263.jpg',
    postCount: 0,
    styles: [
      { label: '포멀', count: 5, color: '#059669' },
      { label: '미니멀', count: 3, color: '#111' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
    ],
    description: '국민 트로트 가수 임영웅의 단정하고 깔끔한 패션. 무대 위 화려한 슈트부터 일상의 단정한 캐주얼까지 임영웅의 신사적인 스타일을 모아봤어요.',
  },
  {
    id: 'chungha',
    name: '청하',
    realName: '김청하',
    category: '가수',
    profileImage: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/CHUNG_HA_Shark_Ninja_PhotoCall_1.jpg/250px-CHUNG_HA_Shark_Ninja_PhotoCall_1.jpg',
    postCount: 0,
    styles: [
      { label: '스트릿', count: 4, color: '#7c3aed' },
      { label: '페미닌', count: 3, color: '#ec4899' },
      { label: '캐주얼', count: 2, color: '#6366f1' },
      { label: '걸리시', count: 2, color: '#f59e0b' },
    ],
    description: '솔로 퀸 청하의 강렬하고 섹시한 패션. 파워풀한 퍼포먼스 의상부터 트렌디한 스트릿 룩까지 청하의 당찬 에너지를 담은 스타일을 살펴보세요.',
  },
];


// GET /api/celebrities
router.get('/', (req, res) => {
  res.json(CELEBRITIES);
});

// GET /api/celebrities/:id
router.get('/:id', (req, res) => {
  const cel = CELEBRITIES.find(c => c.id === req.params.id);
  if (!cel) return res.status(404).json({ error: '연예인 정보를 찾을 수 없습니다.' });
  res.json(cel);
});

export default router;
